version: '3.9'
services:
  # nginx:
  #   restart: always
  #   depends_on:
  #     - dashboard
  #     - client
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   networks:
  #     - webshopper

  dashboard:
    restart: always
    build: 
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - webshop
    networks:
      - webshopper


  client:
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - webshop
    networks:
      - webshopper

  webshop:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - webshopper



networks:
  webshopper:
    driver: bridge
