version: '3'
services:
  dash:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true